### ISSUE TITLE
fix first six ui's "click here for code"

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#120]

**Comment by dissyulina** [comment]
Hi, I would like to fix it. Please assign me, thanks.

**Comment by siddhesh-desai** [comment]
Hello Sir, I have fixed it. Please assign me to add it. Thankyou Sir.

**Comment by Arman-ali-khan-786** [comment]
@dissyulina you made a pr already , did i assigned you ?? there is a protocol to be followed so maintain that , for this action your pr will not be counted ..

**Comment by Arman-ali-khan-786** [comment]
@siddhesh-desai  assigned you

**Comment by dissyulina** [comment]
Hi @Arman-ali-khan-786 , I have asked you to assign me first and since there’s another one commented ready with the fix (eventhough he saw my comment), I guess I’m nervous you’ll assign him instead. Also some maintainers (when they don’t assign a person right away), they open the issue for everyone and the first one to make the PR will get it. And I don’t see any contributing steps (assigned first, then make PR) in the readme, so I thought I can try to make a PR right away. All in all, okay, I’ve made the wrong choice. My bad. I respect your decision.

**Comment by siddhesh-desai** [comment]
Issue fixed @Arman-ali-khan-786 Sir.

**Comment by Arman-ali-khan-786** [comment]
> Hi @Arman-ali-khan-786 , I have asked you to assign me first and since there’s another one commented ready with the fix (eventhough he saw my comment), I guess I’m nervous you’ll assign him instead. Also some maintainers (when they don’t assign a person right away), they open the issue for everyone and the first one to make the PR will get it. And I don’t see any contributing steps (assigned first, then make PR) in the readme, so I thought I can try to make a PR right away. All in all, okay, I’ve made the wrong choice. My bad. I respect your decision.

I don't know about what other's to If you want to contribute to a Open source project you need to be assigned first okkk it the protocol to be followed while doing open source
